export enum SortOption {
    RELEVANCE = 'RELEVANCE',
    POPULARITY = 'POPULARITY',
    PRICE_ASC = 'PRICE_ASC',
    PRICE_DESC = 'PRICE_DESC',
    RELEASE_DATE = 'RELEASE_DATE',
    RATING = 'RATING',
    WISHLIST = 'WISHLIST'
}